//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_clients
    {
        public int ID { get; set; }
        public string Name_of_organization { get; set; }
        public string Organization_data { get; set; }
        public Nullable<int> id_entity { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> id_physical { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Passport_data Passport_data { get; set; }
    }
}
