//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public int Type_of_currency { get; set; }
        public int Type_of_transaction { get; set; }
        public int Amount_of_transaction { get; set; }
        public System.DateTime Date_time_of_transaction { get; set; }
        public int id_transaction { get; set; }
    
        public virtual Indefication_of_transaction Indefication_of_transaction { get; set; }
        public virtual Type_of_currency Type_of_currency1 { get; set; }
        public virtual Type_of_transaction Type_of_transaction1 { get; set; }
    }
}
